'use strict';
const E=window.ClaraEngine,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const paid=[{id:'H-001',counterparty:'Horizonte Serviços',document:'NF 1842',amount:2780,status:'HISTORICO_PAGO'}];
const seed=[
{id:'SOL-001',kind:'Pagamento',counterparty:'Lumen Facilities',document:'NF 418',amount:'3850',issueDate:'2026-09-08',dueDate:'2026-09-28',costCenter:'Administrativo',category:'Serviços',hasDocument:true,notes:'Limpeza mensal'},
{id:'SOL-002',kind:'Reembolso',counterparty:'Marina Costa',document:'REEMB-091',amount:'486.35',issueDate:'2026-09-18',dueDate:'2026-09-30',costCenter:'Comercial',category:'Viagens',hasDocument:false,notes:'Deslocamento para visita'},
{id:'SOL-003',kind:'Pagamento',counterparty:'Horizonte Serviços',document:'NF 1842',amount:'2780',issueDate:'2026-09-10',dueDate:'2026-09-25',costCenter:'Operações',category:'Serviços',hasDocument:true,notes:'Verificar histórico'},
{id:'SOL-004',kind:'Pagamento',counterparty:'Norte Sistemas',document:'FAT 778',amount:'1240.90',issueDate:'2026-09-15',dueDate:'2026-10-05',costCenter:'Projetos',category:'Software',hasDocument:true,notes:'Licenças mensais'}];
let rows=structuredClone(seed),audit=[],view='active',kind='all',timer,editing=null,storageError=false,staged=[],lastSnapshot=null,conflict=false,importSequence=0;
const now=()=>new Date().toISOString();
const paidHistory=()=>[...paid,...rows.filter(r=>r.status==='HISTORICO_PAGO')];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const date=v=>v?String(v).split('-').reverse().join('/'):'—';
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(timer);timer=setTimeout(()=>$('#toast').classList.remove('show'),5500);}
function event(id,action,detail){audit.push({id,at:now(),action,detail});}
function persist(){try{if(conflict||localStorage.getItem('clara.v2')!==lastSnapshot){conflict=true;$('#storage-warning').hidden=false;$('#storage-warning').textContent='Uma outra aba alterou a fila. Faça backup desta sessão e recarregue antes de continuar. Exportação bloqueada.';return false;}const snapshot=JSON.stringify({version:2,rows,audit});localStorage.setItem('clara.v2',snapshot);lastSnapshot=snapshot;return true;}catch{storageError=true;$('#storage-warning').hidden=false;return false;}}
function refresh(){E.reconcile(rows,paidHistory());render();}
function commit(){E.reconcile(rows,paidHistory());persist();render();}
function nextId(offset=0){return 'SOL-'+String(Math.max(0,...rows.map(r=>Number(r.id.slice(4))||0))+1+offset).padStart(3,'0');}
const labels={PRONTO_PARA_CONFERENCIA:'Pronto para conferir',PENDENTE:'Pendente',POSSIVEL_DUPLICIDADE:'Possível duplicidade',CONFERIDO:'Conferido',DESCARTADO:'Descartado',HISTORICO_PAGO:'Pago (simulação)'};
const classes={PRONTO_PARA_CONFERENCIA:'ready',PENDENTE:'pending',POSSIVEL_DUPLICIDADE:'duplicate',CONFERIDO:'confirmed',DESCARTADO:'discarded',HISTORICO_PAGO:'paid'};
function matches(r){if(kind!=='all'&&r.kind!==kind)return false;const q=E.norm($('#search').value);if(q&&!E.norm(r.counterparty+' '+r.document+' '+r.id).includes(q))return false;return view==='ready'?r.status==='PRONTO_PARA_CONFERENCIA':view==='attention'?['PENDENTE','POSSIVEL_DUPLICIDADE'].includes(r.status):view==='confirmed'?r.status==='CONFERIDO':view==='discarded'?r.status==='DESCARTADO':view==='paid'?r.status==='HISTORICO_PAGO':!['DESCARTADO','HISTORICO_PAGO'].includes(r.status);}
function reveal(status){view=status==='HISTORICO_PAGO'?'paid':status==='CONFERIDO'?'confirmed':status==='DESCARTADO'?'discarded':status==='PENDENTE'||status==='POSSIVEL_DUPLICIDADE'?'attention':'ready';kind='all';$('#search').value='';const titles={ready:'Prontos para conferir',attention:'Com atenção',confirmed:'Conferidos',discarded:'Descartados',paid:'Pagos (simulação)',active:'Solicitações em análise'};$('#view-title').textContent=titles[view];$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$$('[data-filter]').forEach(b=>b.classList.toggle('active',b.dataset.filter==='all'));render();}
function render(){const m=E.metrics(rows);for(const [id,value] of Object.entries({'m-total':m.total,'m-amount':money(m.amount),'m-ready':m.ready,'m-attention':m.pending+m.duplicates,'m-time':m.confirmed,'count-active':m.total,'count-ready':m.ready,'count-attention':m.pending+m.duplicates,'count-confirmed':m.confirmed,'count-paid':rows.filter(r=>r.status==='HISTORICO_PAGO').length}))$('#'+id).textContent=value;const filtered=rows.filter(matches);$('#result-count').textContent=filtered.length+' registro(s)';$('#rows').innerHTML=filtered.length?filtered.map(r=>'<tr><td><strong>'+esc(r.id)+'</strong><small>'+esc(r.kind)+'</small></td><td><strong>'+esc(r.counterparty)+'</strong><small>'+esc(r.costCenter)+'</small></td><td>'+esc(r.document)+'</td><td>'+esc(date(r.dueDate))+'</td><td class="money">'+(E.cents(r.amount)===null?'Valor inválido':money(r.amount))+'</td><td><span class="status '+classes[r.status]+'">'+labels[r.status]+'</span></td><td><button class="open" data-open="'+esc(r.id)+'">Abrir</button></td></tr>').join(''):'<tr><td colspan="7" class="empty">Nenhuma solicitação nesta visão.</td></tr>';}
function edit(r){editing=r?.id||null;const f=$('#request-form');f.reset();$('#form-dialog h2').textContent=r?'Editar '+r.id:'Registrar solicitação';$('#form-feedback').textContent=r?'Salvar uma alteração exige nova conferência.':'';if(r)for(const el of f.elements){if(!el.name)continue;if(el.type==='checkbox')el.checked=r[el.name]===true;else{if(el.tagName==='SELECT'&&![...el.options].some(o=>o.value===r[el.name]))el.add(new Option(r[el.name],r[el.name]));el.value=r[el.name]??'';}}$('#form-dialog').showModal();}
$('#new-request').onclick=()=>edit(null);
$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$('#request-form').onsubmit=e=>{e.preventDefault();if(!editing&&rows.length>=2000)return toast('Limite de 2.000 registros nesta demonstração.');const fd=new FormData(e.currentTarget),item=Object.fromEntries(fd);item.hasDocument=fd.has('hasDocument');item.id=editing||nextId();item.createdAt=editing?rows.find(r=>r.id===editing).createdAt:now();if(editing)rows[rows.findIndex(r=>r.id===editing)]=item;else rows.push(item);event(item.id,editing?'Solicitação editada':'Solicitação criada','Encaminhada à triagem; sem aprovação ou pagamento');commit();$('#form-dialog').close();reveal(item.status);toast('Registro salvo e exibido na lista.');};
function openDetail(id){const r=rows.find(x=>x.id===id);if(!r)return;const v=E.validate(r,rows,paidHistory()),discarded=r.status==='DESCARTADO',isPaid=r.status==='HISTORICO_PAGO',inactive=discarded||isPaid,confirmed=E.canExport(r,rows,paidHistory());const events=audit.filter(x=>x.id===id).slice().reverse();
$('#detail').innerHTML='<div class="dialog-head"><div><p class="eyebrow">'+esc(r.id)+' · '+esc(r.kind)+'</p><h2>'+esc(r.counterparty)+'</h2></div><button class="close" data-detail-close aria-label="Fechar">×</button></div><div class="detail-body"><div class="detail-grid">'+[['Documento',r.document],['Valor',E.cents(r.amount)===null?'Inválido':money(r.amount)],['Emissão',date(r.issueDate)],['Vencimento',date(r.dueDate)],['Centro de custo',r.costCenter],['Categoria',r.category]].map(([k,val])=>'<div><small>'+k+'</small>'+esc(val)+'</div>').join('')+'</div><p>'+esc(r.notes)+'</p><div class="issues"><strong>Triagem: '+labels[r.status]+'</strong><p>'+([...v.errors,...v.warnings].map(esc).join('<br>')||'Sem pendências automáticas. Isso não valida a autenticidade do documento.')+'</p><p>Documento recebido: '+(r.hasDocument?'declarado manualmente':'não declarado')+'. Nenhum arquivo é anexado ou lido por esta aplicação.</p>'+(v.warnings.length?'<p>Duplicidades permanecem bloqueadas. Confira a origem, corrija um erro de cadastro ou descarte a solicitação repetida. Não altere campos apenas para contornar o alerta.</p>':'')+'</div>'+(isPaid?'<div class="issues"><strong>Baixa fictícia</strong><p>Data: '+esc(date(r.paidDate))+' · Referência: '+esc(r.paidReference)+'</p><p>Nenhum pagamento foi executado pela aplicação.</p></div>':'')+'<div id="detail-feedback" class="feedback" role="status" aria-live="polite"></div>'+(!inactive?'<div class="form-grid"><label>Conferente (identificação declarada)<input id="reviewer" maxlength="100" value="'+esc(r.review?.reviewer||'')+'"></label><label>Justificativa / referência da conferência<textarea id="reason" maxlength="1000">'+esc(r.review?.reason||'')+'</textarea></label><label class="wide check"><input id="checked" type="checkbox"> Conferi os dados e o documento de origem. Entendo que isto não autoriza pagamento.</label></div>':'')+'<div class="audit"><strong>Histórico local — não é uma trilha inviolável</strong><ul>'+events.map(x=>'<li>'+esc(x.at)+' — '+esc(x.action)+': '+esc(x.detail)+'</li>').join('')+'</ul></div></div><div class="detail-actions">'+(!inactive?'<button class="secondary" data-edit>Editar</button><button class="danger" data-discard>Excluir da fila</button>'+(confirmed?'<button class="secondary" data-pay>Registrar baixa fictícia</button>':'')+'<button class="primary" data-confirm '+(confirmed?'disabled':'')+'>'+(confirmed?'Já conferido':'Conferir solicitação')+'</button>':discarded?'<button class="secondary" data-restore>Restaurar à fila</button>':'')+'<button class="secondary" data-detail-close>Fechar</button></div>';
if(!$('#detail-dialog').open)$('#detail-dialog').showModal();$$('[data-detail-close]').forEach(b=>b.onclick=()=>$('#detail-dialog').close());
if(discarded){$('[data-restore]').onclick=()=>{r.status=E.validate(r,rows,paidHistory()).status;event(id,'Restauração da fila','Item restaurado para nova triagem');commit();$('#detail-dialog').close();reveal(r.status);toast('Item restaurado e reavaliado.');};return;}if(isPaid)return;
if(confirmed)$('[data-pay]').onclick=()=>{$('#pay-name').textContent=r.id+' · '+r.counterparty+' · '+money(r.amount);$('#pay-date').value=new Date().toISOString().slice(0,10);$('#pay-reference').value='';$('#pay-feedback').textContent='';$('#pay-dialog').showModal();$('#pay-yes').onclick=()=>{const paidDate=$('#pay-date').value,paidReference=$('#pay-reference').value.trim();if(!/^\d{4}-\d{2}-\d{2}$/.test(paidDate)||paidReference.length<3){$('#pay-feedback').textContent='Informe uma data e referência fictícia com pelo menos 3 caracteres.';return;}if(!E.canExport(r,rows,paidHistory())){$('#pay-feedback').textContent='A conferência precisa ser refeita antes da baixa.';return;}r.status='HISTORICO_PAGO';r.paidDate=paidDate;r.paidReference=paidReference;event(id,'Baixa fictícia','Data '+paidDate+' · '+paidReference+' · Nenhum pagamento executado');commit();$('#pay-dialog').close();$('#detail-dialog').close();reveal(r.status);toast('Baixa registrada apenas na demonstração.');};};
$('[data-edit]').onclick=()=>{$('#detail-dialog').close();edit(r);};
$('[data-discard]').onclick=()=>{$('#delete-name').textContent=r.id+' · '+r.counterparty;$('#delete-reason').value='';$('#delete-dialog').showModal();$('#delete-yes').onclick=()=>{const reason=$('#delete-reason').value.trim();r.status='DESCARTADO';delete r.review;event(id,'Exclusão da fila',reason||'Excluído manualmente; recuperação disponível');commit();$('#delete-dialog').close();$('#detail-dialog').close();reveal(r.status);toast('Item excluído da fila. Você pode restaurá-lo em Descartados.');};};
$('[data-confirm]').onclick=()=>{const reason=$('#reason').value.trim(),reviewer=$('#reviewer').value.trim();const check=E.validate(r,rows,paidHistory());if(check.errors.length||check.warnings.length){$('#detail-feedback').textContent='Antes de conferir: '+[...check.errors,...check.warnings].join(' · ')+'. Use Editar para corrigir os dados ou a declaração do documento.';return;}if(!reviewer||reason.length<10||!$('#checked').checked){$('#detail-feedback').textContent='Informe o conferente, escreva uma justificativa com ao menos 10 caracteres e marque a declaração de conferência.';return;}r.review={reviewer,reason,at:now(),fingerprint:E.fingerprint(r)};r.status='CONFERIDO';event(id,'Conferência declarada',reviewer+': '+reason);commit();$('#detail-dialog').close();reveal(r.status);toast('Conferência registrada. Nenhum pagamento executado.');};
}
document.addEventListener('click',e=>{const o=e.target.closest('[data-open]');if(o)openDetail(o.dataset.open);const b=e.target.closest('[data-view]');if(b){view=b.dataset.view;$$('[data-view]').forEach(x=>x.classList.toggle('active',x===b));$('#view-title').textContent=b.textContent.replace(/\d+/g,'').trim();refresh();}const f=e.target.closest('[data-filter]');if(f){kind=f.dataset.filter;$$('[data-filter]').forEach(x=>x.classList.toggle('active',x===f));refresh();}});
$('#search').oninput=render;
function download(name,text,type){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([text],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('#export').onclick=()=>{if(conflict)return toast('Recarregue a página para resolver o conflito entre abas.');try{if(localStorage.getItem('clara.v2')!==lastSnapshot){conflict=true;return toast('A fila mudou em outra aba. Recarregue antes de exportar.');}}catch{}refresh();const selected=rows.filter(r=>E.canExport(r,rows,paidHistory()));if(!selected.length)return toast('Nenhum registro elegível. A conferência humana é obrigatória.');download('clara-conferidos.csv',E.csv(selected),'text/csv;charset=utf-8');event('LOTE','Exportação CSV',selected.map(r=>r.id).join(', '));persist();toast(selected.length+' registro(s) exportado(s), de todas as visões.');};
$('#backup').onclick=()=>{download('clara-backup.json',JSON.stringify({version:2,fictional:true,exportedAt:now(),rows,audit,paid},null,2),'application/json');toast('Backup JSON baixado. Verifique os downloads do navegador.');};
// The demo stores a single snapshot. Legacy data is preserved and re-triaged, never trusted as approval.
try{const saved=localStorage.getItem('clara.v2');lastSnapshot=saved;const legacy=!saved&&localStorage.getItem('clara.rows');if(saved||legacy){const state=saved?JSON.parse(saved):{rows:JSON.parse(legacy),audit:[]};if(!E.validSnapshot({...state,version:2}))throw Error('Formato inválido');rows=state.rows;audit=state.audit.filter(a=>a&&typeof a.id==='string'&&typeof a.at==='string');if(legacy)event('SISTEMA','Migração','Conferências antigas exigem nova revisão; arquivos anteriores preservados.');}}catch{storageError=true;}
const banner=document.createElement('p');banner.id='storage-warning';banner.className='issues';banner.hidden=!storageError;banner.textContent='Armazenamento indisponível ou inválido. Esta sessão está em memória: faça backup antes de fechar. Os dados anteriores não serão sobrescritos.';$('main').prepend(banner);
if(storageError)persist=()=>false;
$('.gain span').textContent='Conferidos para exportação';$('.gain small').textContent='Revalidados antes de gerar o CSV';
$('.method details p').textContent='Dados fictícios e armazenamento local neste navegador. Identidade do conferente autodeclarada, sem autenticação. O histórico pode ser alterado por quem tem acesso ao navegador e não é uma trilha de auditoria inviolável. Não há leitura de anexos, aprovação, ERP ou pagamento. Duplicidade: favorecido, documento e valor normalizados iguais, sem considerar emissão; é um indício conservador, não uma prova. Uso real exige validação das regras, autenticação, banco, controle de acesso, retenção e backups. Não há economia de tempo comprovada nesta demonstração.';
const docLabel=$('[name="hasDocument"]').parentElement;docLabel.lastChild.textContent=' Declaro que recebi o documento (não há upload de anexo)';
$('#views').insertAdjacentHTML('beforeend','<button data-view="discarded">Descartados</button><button data-view="paid">Pagos (simulação) <b id="count-paid">0</b></button>');
$('.actions').insertAdjacentHTML('beforeend','<button class="secondary" id="import">Importar CSV</button><button class="secondary" id="template">Modelo CSV</button>');
const batch=document.createElement('dialog');batch.id='batch-dialog';batch.innerHTML='<div class="dialog-head"><h2>Importar lote fictício</h2><button class="close" id="batch-close" aria-label="Fechar">×</button></div><div class="detail-body"><p>UTF-8, separado por ponto e vírgula. Até 500 registros / 1 MB. Datas AAAA-MM-DD; valores sem separador de milhar. Nenhum item entra conferido.</p><input type="file" id="csv-file" accept=".csv,text/csv"><p id="batch-summary" role="status"></p><div id="batch-preview"></div></div><div class="detail-actions"><button class="primary" id="batch-commit" disabled>Adicionar à fila de triagem</button></div>' ;document.body.append(batch);
$('#import').onclick=()=>{staged=[];$('#csv-file').value='';$('#batch-summary').textContent='Selecione o arquivo para visualizar antes de importar.';$('#batch-preview').innerHTML='';$('#batch-commit').disabled=true;batch.showModal();};
$('#batch-close').onclick=()=>{importSequence++;staged=[];batch.close();};
$('#template').onclick=()=>{download('clara-modelo.csv','\uFEFF'+E.headers.join(';')+'\r\nPagamento;Fornecedor Exemplo;NF 900;120,50;2026-09-01;2026-09-30;Administrativo;Serviços;sim;Exemplo inteiramente fictício\r\n','text/csv;charset=utf-8');toast('Modelo CSV baixado. Verifique os downloads do navegador.');};
$('#csv-file').onchange=async e=>{const sequence=++importSequence;staged=[];$('#batch-commit').disabled=true;$('#batch-preview').innerHTML='';try{const file=e.target.files[0];if(!file)return;if(file.size>1000000)throw Error('Limite de 1 MB');const contents=await file.text();if(sequence!==importSequence)return;const parsed=E.parseCSV(contents);if(rows.length+parsed.length>2000)throw Error('Limite de 2.000 registros na demonstração');staged=parsed.map((r,i)=>({...r,id:nextId(i),createdAt:now()}));const all=[...rows,...staged];const results=staged.map(r=>E.validate(r,all,paidHistory()));$('#batch-summary').textContent=staged.length+' registro(s); '+results.filter(v=>v.errors.length||v.warnings.length).length+' com atenção. Pendências entram bloqueadas na fila.';$('#batch-preview').innerHTML=staged.map((r,i)=>'<p><strong>'+esc(r.counterparty)+'</strong> · '+esc(r.document)+'<br>'+esc([...results[i].errors,...results[i].warnings].join(' · ')||'Pronto para conferência humana')+'</p>').join('');$('#batch-commit').disabled=!staged.length;}catch(err){$('#batch-summary').textContent=err.message;}};
$('#batch-commit').onclick=()=>{if(!staged.length)return;const n=staged.length;for(const r of staged){r.id=nextId();rows.push(r);event(r.id,'Importação CSV','Recebido para triagem; não conferido');}staged=[];commit();batch.close();view='active';kind='all';$('#search').value='';$('#view-title').textContent='Solicitações em análise';$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view==='active'));$$('[data-filter]').forEach(b=>b.classList.toggle('active',b.dataset.filter==='all'));render();toast(n+' solicitações adicionadas e exibidas na fila.');};
refresh();
window.addEventListener('storage',ev=>{if(ev.key==='clara.v2'){conflict=true;$('#storage-warning').hidden=false;$('#storage-warning').textContent='Outra aba alterou a fila. Faça backup desta sessão e recarregue. Exportação bloqueada até recarregar.';}});
$('#batch-dialog .detail-body').insertAdjacentHTML('afterbegin','<button class="secondary" id="sample-batch">Experimentar lote fictício</button>');
$('#sample-batch').onclick=()=>{importSequence++;const sample=[{...seed[0],document:'NF DEMO 901',amount:'250.50'},{...seed[1],document:'REEMB DEMO 902'},{...seed[2]}];if(rows.length+sample.length>2000)return toast('Limite da demonstração atingido.');staged=sample.map((r,i)=>({...r,id:nextId(i),createdAt:now()}));const all=[...rows,...staged];$('#batch-summary').textContent='3 exemplos fictícios: item regular, documento pendente e duplicidade no histórico. Revise antes de adicionar.';$('#batch-preview').innerHTML=staged.map(r=>'<p><strong>'+esc(r.counterparty)+'</strong> · '+esc(r.document)+'<br>'+esc([...E.validate(r,all,paidHistory()).errors,...E.validate(r,all,paidHistory()).warnings].join(' · ')||'Pronto para conferência humana')+'</p>').join('');$('#batch-commit').disabled=false;};
const help=document.createElement('section');help.className='quickstart';help.innerHTML='<div><p class="eyebrow">EXPERIMENTE EM 2 MINUTOS</p><h2>Da entrada à conferência, sem executar pagamentos.</h2><p>1. Importe um lote fictício. 2. Veja as pendências. 3. Confira um item regular. 4. Exporte o CSV.</p><small>Use apenas dados fictícios. Os registros ficam neste navegador; não são compartilhados entre visitantes. Nenhuma economia de tempo é prometida.</small></div><button class="secondary" id="try-demo">Testar lote de exemplo</button>';$('main .metrics').before(help);$('#try-demo').onclick=()=>{$('#import').click();$('#sample-batch').click();};
$$('.steps p')[1].textContent='Campos, datas, declaração de documento e indícios de duplicidade.';
$('#m-amount').title='Soma dos valores válidos da fila ativa; não representa saldo bancário.';
document.addEventListener('keydown',ev=>{if(ev.key==='Escape')importSequence++;});
const removeDialog=document.createElement('dialog');removeDialog.id='delete-dialog';removeDialog.innerHTML='<div class="dialog-head"><h2>Excluir da fila?</h2><button class="close" id="delete-close" aria-label="Fechar">×</button></div><div class="detail-body"><p id="delete-name"></p><p>O registro sai da fila ativa e pode ser restaurado na visão Descartados. Nenhum pagamento será alterado.</p><label>Motivo (opcional)<textarea id="delete-reason" rows="2" maxlength="500"></textarea></label></div><div class="detail-actions"><button class="secondary" id="delete-cancel">Cancelar</button><button class="danger" id="delete-yes">Excluir da fila</button></div>';document.body.append(removeDialog);$('#delete-close').onclick=$('#delete-cancel').onclick=()=>removeDialog.close();
const payDialog=document.createElement('dialog');payDialog.id='pay-dialog';payDialog.innerHTML='<div class="dialog-head"><h2>Registrar baixa fictícia</h2><button class="close" id="pay-close" aria-label="Fechar">×</button></div><div class="detail-body"><p id="pay-name"></p><p>Essa ação muda somente o estado deste exemplo no navegador. Não realiza pagamento.</p><div class="form-grid"><label>Data da baixa<input id="pay-date" type="date" required></label><label>Referência fictícia<input id="pay-reference" maxlength="100" placeholder="Ex.: DEMO-001" required></label></div><div id="pay-feedback" class="feedback" role="status"></div></div><div class="detail-actions"><button class="secondary" id="pay-cancel">Cancelar</button><button class="primary" id="pay-yes">Registrar baixa</button></div>';document.body.append(payDialog);$('#pay-close').onclick=$('#pay-cancel').onclick=()=>payDialog.close();
