(function(root){
'use strict';
const norm=v=>String(v??'').trim().toLocaleUpperCase('pt-BR').replace(/\s+/g,' ');
const fields=['kind','counterparty','document','amount','issueDate','dueDate','costCenter','category','hasDocument','notes'];
function cents(v){const s=String(v);if(!/^\d+(\.\d{1,2})?$/.test(s))return null;const [a,b='']=s.split('.');const n=Number(a)*100+Number(b.padEnd(2,'0'));return Number.isSafeInteger(n)&&n>0&&n<=99999999999?n:null;}
function validDate(s){try{return /^\d{4}-\d{2}-\d{2}$/.test(s||'')&&Number(s.slice(0,4))>=1900&&Number(s.slice(0,4))<=2100&&new Date(s+'T12:00:00Z').toISOString().slice(0,10)===s;}catch{return false;}}
function duplicateKey(r){return [norm(r.counterparty),norm(r.document).replace(/[\s.-]/g,''),cents(r.amount)].join('|');}
function fingerprint(r){return JSON.stringify(fields.map(k=>r[k]??''));}
function validate(item,all=[],paid=[]){const errors=[],warnings=[];for(const k of fields.slice(0,8))if(!String(item[k]??'').trim())errors.push('Campo obrigatório: '+k);if(cents(item.amount)===null)errors.push('Valor inválido: até duas casas decimais, maior que zero e até R$ 999.999.999,99');for(const k of ['issueDate','dueDate'])if(!validDate(item[k]))errors.push('Data inválida: '+k);if(item.dueDate<item.issueDate)errors.push('Vencimento anterior à emissão');if(!['Pagamento','Reembolso'].includes(item.kind))errors.push('Tipo desconhecido');if(item.hasDocument!==true)errors.push('Recebimento do documento não declarado');const key=duplicateKey(item);if(all.some(r=>r.id!==item.id&&!['DESCARTADO','HISTORICO_PAGO'].includes(r.status)&&duplicateKey(r)===key))warnings.push('Possível duplicidade na fila: favorecido, documento e valor iguais');if(paid.some(r=>r.id!==item.id&&duplicateKey(r)===key))warnings.push('Possível duplicidade com histórico pago');return {errors,warnings,status:errors.length?'PENDENTE':warnings.length?'POSSIVEL_DUPLICIDADE':'PRONTO_PARA_CONFERENCIA'};}
function canExport(r,all,paid){const v=validate(r,all,paid);return r.status==='CONFERIDO'&&!v.errors.length&&!v.warnings.length&&r.review?.fingerprint===fingerprint(r)&&typeof r.review?.reviewer==='string'&&!!r.review.reviewer.trim()&&typeof r.review?.reason==='string'&&r.review.reason.trim().length>=10;}
function reconcile(rows,paid){for(const r of rows){if(['DESCARTADO','HISTORICO_PAGO'].includes(r.status))continue;if(!canExport(r,rows,paid)){r.status=validate(r,rows,paid).status;delete r.review;}}return rows;}
function metrics(rows){const active=rows.filter(r=>!['DESCARTADO','HISTORICO_PAGO'].includes(r.status));return {total:active.length,ready:active.filter(r=>r.status==='PRONTO_PARA_CONFERENCIA').length,pending:active.filter(r=>r.status==='PENDENTE').length,duplicates:active.filter(r=>r.status==='POSSIVEL_DUPLICIDADE').length,confirmed:active.filter(r=>r.status==='CONFERIDO').length,amount:active.reduce((s,r)=>s+(cents(r.amount)||0),0)/100,minutesSaved:active.length*2};}
function csv(rows){const safe=v=>'"'+String(v??'').replace(/^(\s*)([=+@\-\t\r])/u,"'$1$2").replace(/"/g,'""')+'"';return '\uFEFF'+[['id','tipo','favorecido','documento','valor','emissao','vencimento','centro_custo','categoria','status','observacao','conferente','justificativa','conferido_em'],...rows.map(r=>[r.id,r.kind,r.counterparty,r.document,((cents(r.amount)||0)/100).toFixed(2).replace('.',','),r.issueDate,r.dueDate,r.costCenter,r.category,r.status,r.notes,r.review?.reviewer,r.review?.reason,r.review?.at])].map(row=>row.map(safe).join(';')).join('\r\n');}
const headers=['tipo','favorecido','documento','valor','emissao','vencimento','centro_custo','categoria','documento_recebido','observacao'];
function parseCSV(text){if(text.length>1000000)throw Error('Limite de 1 MB por arquivo');text=text.replace(/^\uFEFF/,'');const lines=[];let row=[],value='',quoted=false,closed=false;for(let i=0;i<text.length;i++){const c=text[i];if(quoted){if(c==='"'&&text[i+1]==='"'){value+='"';i++;}else if(c==='"'){quoted=false;closed=true;}else value+=c;}else if(c==='"'&&!value&&!closed){quoted=true;}else if(c===';'||c==='\n'||c==='\r'){row.push(value);value='';closed=false;if(c!==';'){if(c==='\r'&&text[i+1]==='\n')i++;if(row.some(x=>x.trim()))lines.push(row);row=[];}}else{if(closed||c==='"')throw Error('Aspas inválidas no CSV');value+=c;}}if(quoted)throw Error('Aspas não fechadas');row.push(value);if(row.some(x=>x.trim()))lines.push(row);if(lines.length>501)throw Error('Limite de 500 solicitações');const h=lines.shift()?.map(x=>x.trim());if(JSON.stringify(h)!==JSON.stringify(headers))throw Error('Cabeçalho diferente do modelo. Baixe o modelo disponível.');return lines.map((a,i)=>{if(a.length!==headers.length)throw Error('Quantidade de colunas incorreta no registro '+(i+2));if(!['sim','nao','não'].includes(a[8].trim().toLowerCase()))throw Error('Documento recebido deve ser sim ou não no registro '+(i+2));return {kind:a[0].trim(),counterparty:a[1].trim(),document:a[2].trim(),amount:a[3].trim().replace(',','.'),issueDate:a[4].trim(),dueDate:a[5].trim(),costCenter:a[6].trim(),category:a[7].trim(),hasDocument:a[8].trim().toLowerCase()==='sim',notes:a[9].trim()};});}
function validSnapshot(s){return s&&s.version===2&&Array.isArray(s.rows)&&s.rows.length<=2000&&Array.isArray(s.audit)&&s.audit.length<=20000&&s.rows.every(r=>r&&typeof r.id==='string'&&/^SOL-\d{1,9}$/.test(r.id)&&fields.every(k=>r[k]===undefined||typeof r[k]==='string'||typeof r[k]==='number'||typeof r[k]==='boolean')&&(!r.review||(typeof r.review==='object'&&typeof r.review.reviewer==='string'&&typeof r.review.reason==='string')))&&new Set(s.rows.map(r=>r.id)).size===s.rows.length;}
const api={validSnapshot,norm,cents,duplicateKey,fingerprint,validate,canExport,reconcile,metrics,csv,parseCSV,headers};if(typeof module!=='undefined')module.exports=api;else root.ClaraEngine=api;
})(typeof window!=='undefined'?window:globalThis);
